name: "PL - Closed"
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  up-version:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN || github.token }}

      - name: Git config settings
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Git pull
        run: git pull

      - name: Git checkout
        run: git checkout main

      - name: Git branch
        run: git branch

      - name: Status
        run: git status

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Apply verrsion bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: npm version major

      - name: Apply verrsion bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm version minor

      - name: Apply verrsion bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: npm version patch

      - name: Git push version bump
        run: git push origin main --force

      - name: Version change
        run: npm pkg get version
