on:
  pull_request:
    branches:
      - main

jobs:
  up-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name" && npm version patch && git commit -m "Update Version" && git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "${{ github.head_ref }}"
