on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  up-version:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Git config settings
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Git branch
        run: git branch

      - name: Git pull
        run: git pull

      - name: Git checkout
        run: git checkout origin/main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm version patch && git show && git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" origin/main
